baseurl = "https://elim.github.io/"
title = "IDIC"
theme = "ghostwriter"
languageCode = "ja-jp"
copyright = "Takeru Naito"
googleAnalytics = "UA-90004615-1"
# disqusShortname = "XXX"

[Author]
    name = "Takeru Naito"
    profile = "https://facebook.com/takeru"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "IDIC"
    description = "Infinite Diversity in Infinite Combinations."
    github = "https://github.com/elim"
    linkedin = "https://www.linkedin.com/in/takerunaito/"
    gplus = "https://google.com/+takerunaito"
    twitter = "https://twitter.com/elim"
    opengraph = true

[Permalinks]
    post  = "/:year/:month/:day/:slug"
    fixed = "/:slug"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

# [[menu.main]]
#     name = "Projects"
#     url = "/project/"
#     weight = 2

# [[menu.main]]
#     name = "Contact"
#     url = "/page/contact/"
#     weight = 3

