---
Author:
  facebook: takeru
  github: elim
  instagram: tailor.elim
  name: Takeru Naito
  twitter: elim
BaseURL: https://elim.github.io/
Copyright: elim
DefaultContentLanguage: ja
GoogleAnalytics: UA-90004615-1
hasCJKLanguage: true
LanguageCode: ja
Menu:
  Main:
  - name: Blog
    url: "/"
    weight: 1
  - name: About
    url: "/page/about/"
    weight: 2
MetaDataFormat: yaml
Params:
  subtitle: Infinite Diversity in Infinite Combinations
  logo: media/favicons/favicon-96x96.png
Permalinks:
  fixed: "/:slug"
  post: "/:year/:month/:day/:slug"
PygmentsUseClasses: true
PygmentCodeFences: true
Taxonomies:
  tag: tags
enableEmoji: True
rssLimit: 3
theme: beautifulhugo
title: IDIC
