---
Author:
  name: Takeru Naito
  profile: https://facebook.com/takeru
MetaDataFormat: yaml
Params:
  description: Infinite Diversity in Infinite Combinations.
  github: https://github.com/elim
  gplus: https://google.com/+takerunaito
  headline: IDIC
  intro: true
  linkedin: https://www.linkedin.com/in/takerunaito/
  opengraph: true
  twitter: https://twitter.com/elim
Permalinks:
  fixed: "/:slug"
  post: "/:year/:month/:day/:slug"
Taxonomies:
  tag: tags
BaseURL: https://elim.github.io/
Copyright: Takeru Naito
GoogleAnalytics: UA-90004615-1
LanguageCode: ja-jp
Menu:
  Main:
  - name: Blog
    url: "/"
    weight: 1
  - name: About
    url: "/page/about/"
    weight: 2
hasCJKLanguage: true
theme: ghostwriter
title: IDIC
